version: "3.7"
services:
  postgres:
    image: postgres:13
    env_file:
      - ./server/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

volumes:
  postgres:
    name: selections-db
